version: '3.8'
services:
  app:
    build:
      context: src
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - REDIS_URL=${REDIS_URL}
      - JWT_SECRET=${JWT_SECRET}
      - JWT_EXPIRES_IN=${JWT_EXPIRES_IN}
      - NODE_ENV=development
    depends_on:
      - db
      - redis

  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ab12cd34
      POSTGRES_DB: db_dev
    volumes:
      - dev_db_data:/var/lib/postgresql/data
    ports:
      - "5430:5432"

  redis:
    image: redis:latest
    volumes:
      - dev_redis_data:/data
    ports:
      - "6359:6379"

volumes:
  dev_db_data:
  dev_redis_data:
